### ISSUE TITLE
Unexpected comma in title

### ISSUE THREAD

**Issue by corydeppen** [nfl/react-helmet#408]
Similar to #286, I continue to see a comma in the title of pages of my Gatsby app and seems to only be a problem if there's an expression in the `title`. A reproduction of this issue can be seen in the following branch.

https://github.com/corydeppen/gatsby-8655-example/tree/react-helmet-comma

**Comment by edorivai** [comment]
I am seeing both stray commas (`,`), as well as html comments (`<!-- -->`).

I've worked around it by using the `titleTemplate` feature, which completely removed our need to do interpolation.

**Comment by AubreyHewes** [comment]
@corydeppen This problem _seems_ to have been fixed a long time ago see pr #351. Merged in to the master by @jamsea, The major problem here is that there has not been a new release/npm/maintenance for about a year (#391).  So you are probably using the latest version from npm from before the possible fix was merged to the master...

Could you possibly create a test against the master?

fyi @tmbtech @cwelch5

Also possible issue template requesting used version?

**Comment by chez14** [comment]
Any updates? I'm still experiencing this issue.
```yaml
react-helmet@^5.2.0:
  version "5.2.0"
  resolved "https://registry.yarnpkg.com/react-helmet/-/react-helmet-5.2.0.tgz#a81811df21313a6d55c5f058c4aeba5d6f3d97a7"
  integrity sha1-qBgR3yExOm1VxfBYxK66XW89l6c=
  dependencies:
    deep-equal "^1.0.1"
    object-assign "^4.1.1"
    prop-types "^15.5.4"
    react-side-effect "^1.1.0"
```

Code:
```js
<Helmet {...helmet}>
   <title>{username + " - " + ujian} Ujian</title>
</Helmet>
```

result:
```html
<title>i16011 - AIF000000, Ujian</title>
```

**Comment by vcarl** [comment]
Also still encountering this with latest version. Minimal repro is a handful of lines:

```js
import React from "react";
import ReactDOM from "react-dom";
import Helmet from "react-helmet";

function App() {
  const string = "string";
  return (
    <div>
      <Helmet titleTemplate="%s - template">
        <title>'{string}' not string</title>
      </Helmet>
      butts
    </div>
  );
}
```

https://nbolv.codesandbox.io/

https://codesandbox.io/s/nbolv

![Screen Shot 2019-05-21 at 4 22 35 PM](https://user-images.githubusercontent.com/1551487/58127995-a99e6200-7be4-11e9-8593-f94bd347511d.png)

**Comment by vcarl** [comment]
Nevermind! I hunted it down. `master` [appears to have a fix](https://github.com/nfl/react-helmet/blob/release/5.2.0/src/HelmetUtils.js#L36)—but [hasn't been backported to `5.2.1`](https://github.com/nfl/react-helmet/blob/release/5.2.0/src/HelmetUtils.js#L36). Opened a PR.

**Comment by TimboKZ** [comment]
As a temp solution, replacing `<title>` contents with a single string seems to solve the problem:
```jsx
<Helmet>
    <title>{`${summary.name} collection`}</title>
</Helmet>
```

**Comment by AubreyHewes** [comment]
If this has been solved, why has it not been resolved....? https://github.com/nfl/react-helmet/issues/391
If this has not been solved, why not?

**Comment by ajayunnikuttan** [comment]
I had updated the version to  6.1.0 and the issue is resolved
