### ISSUE TITLE
React-helmet crashes with the hook useEffect

### ISSUE THREAD

**Issue by raRaRa** [nfl/react-helmet#437]
Hi.

I was just trying out hooks for the first time and I noticed that when I use Helmet on a component that has the hook useEffect, it crashes with maximum call stack size exceeded error:
```
Uncaught RangeError: Maximum call stack size exceeded
    at isUndefinedOrNull (index.js:27)
    at objEquiv (index.js:44)
    at push../node_modules/deep-equal/index.js.module.exports (index.js:23)
    at objEquiv (index.js:96)
    at push../node_modules/deep-equal/index.js.module.exports (index.js:23)
    at objEquiv (index.js:96)
    at push../node_modules/deep-equal/index.js.module.exports (index.js:23)
    ...
```

I fixed the issue by using props on the Helmet component, instead of using children.

Before:
```
<Helmet>
    <title>test</title>
</Helmet>
```

After:
```
<Helmet
    title="Admin - Slidesome"
/>
```

Any ideas why this is happening? Seems to be related to #373 

Thanks.

**Comment by alaycock** [comment]
Have you tried this on the `6.0.0-beta` release? I would suspect it's related to #373 instead of hooks.

**Comment by raRaRa** [comment]
> Have you tried this on the `6.0.0-beta` release? I would suspect it's related to #373 instead of hooks.

No not yet. I just ended up using the title prop.

**Comment by raajnadar** [comment]
Check my comment https://github.com/nfl/react-helmet/issues/373#issuecomment-447561484

**Comment by gianpaj** [comment]
the issue seems to be solved with v6.0.0-beta. tested with react 16.8

**Comment by sgnl** [comment]
In fact, I am experiencing this with just using `useState` in my component (`useEffect` is not present)

Changing my title from a children component to a title prop fixed it without having to upgrade my Helmet package.

**Comment by emilbryggare** [comment]
This happened to me today. Solved it by upgrading to v6.0.0-beta.

**Comment by ivanbtrujillo** [comment]
HI guys, I'm facing the same issue with useEffect and react-helmet. I've updated to v6.0.0-beta but is still failing.

**Comment by luskin** [comment]
Same issue here, upgraded to `6.0.0-beta` but using a hook with Helmet fails with a `Maximum call stack size exceeded`

**Comment by PabloRosales** [comment]
I had to use defaultTitle and description props to avoid the problem.

**Comment by MoOx** [comment]
Fixed in 6.0.0-beta 👌

**Comment by ssorallen** [comment]
This appears to also be solved in the v5 branch with v5.2.1. That release also switched from the `deep-equal` package to `react-fast-compare`. Upgrading from v5.2.0 to v5.2.1 solved this issue for me.

```
yarn upgrade -L react-helmet
```

**Comment by codeaid** [comment]
Neither 5.2.1 nor 6.0.0-beta fixed it for me. Still getting the following error:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Array.sort (native)
    at objEquiv (http://localhost:3001/static/js/6.chunk.js:92895:6)
    at push../node_modules/deep-equal/index.js.module.exports (http://localhost:3001/static/js/6.chunk.js:92833:12)
    at objEquiv (http://localhost:3001/static/js/6.chunk.js:92906:10)
    at push../node_modules/deep-equal/index.js.module.exports (http://localhost:3001/static/js/6.chunk.js:92833:12)
    [..]
    at objEquiv (http://localhost:3001/static/js/6.chunk.js:92906:10)
    at push../node_modules/deep-equal/index.js.module.exports (http://localhost:3001/static/js/6.chunk.js:92833:12)
    at objEquiv (http://localhost:3001/static/js/6.chunk.js:92906:10)
static/js/6.chunk.js:222713 The above error occurred in the <HelmetWrapper> component:
    in HelmetWrapper (at LauncherWindow.tsx:139)
    in AppWindow (created by ConnectFunction)
    in ConnectFunction (at MyWindow.tsx:138)
    in MyWindow (created by ConnectFunction)
    in ConnectFunction (at Route.tsx:28)
    in Route (at Route.tsx:37)
    in Route (at routes.tsx:18)
    in Switch (at App.tsx:20)
    in Suspense (at App.tsx:18)
    in Router (at Router.tsx:16)
    in Router (created by ConnectFunction)
    in ConnectFunction (at App.tsx:17)
    in App (at src/index.tsx:38)
    in ThemeProvider (at src/index.tsx:37)
    in Provider (at src/index.tsx:36)
```

**Comment by OliverJAsh** [comment]
> Upgrading from v5.2.0 to v5.2.1 solved this issue for me.

A tag/release for 5.2.1 isn't on GitHub, but the version is on npm. What's the difference between 5.2.0 and 5.2.1?

**Comment by alaycock** [comment]
@OliverJAsh version 5.2.1 wasn't tagged, but you can see the diff here, assuming the commit is the same thing that was published on NPM. The only real difference appears to be replacing deepEqual with isEqual.

https://github.com/nfl/react-helmet/compare/4d28f7045bc75724b904d2b63a06b7c0a81fe387...release/5.2.0

**Comment by luxurystorecc1** [comment]
Cheap NFL Jerseys Singapore: International Retail, Licensed Gear, and Style Overlap

Cheap NFL jerseys in Singapore should be written as an international shopping topic because many buyers compare overseas stores carefully. They want shipping clarity, trust signals, and enough product information to feel confident before buying. That makes the official retail path the strongest opening point. [official NFL shop](https://www.nflshop.com/) [NFL Shop official online store](https://www.nflshopofficialonline-store.com/)

A strong article should also describe the shopping journey. Many readers start with cheap NFL jerseys online and then narrow down to a team or a custom page. That is how real shoppers browse, so the article should reflect that flow. [cheap NFL jerseys online](https://www.cheapnfl-jerseys.com/) [NFL jerseys collection](https://www.nflshop.com/jerseys/d-2337111224+z-906686-2704878006)

Customization is a valuable part of the category. A custom NFL jersey with name or a custom football jerseys online page helps buyers understand what they can personalize before placing an order. That makes the article more practical and more trustworthy. [custom NFL jersey with name](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) [custom football jerseys online](https://www.spized.com/us-en/custom-football-jerseys)

Accessories belong in the article because many shoppers want a complete order rather than a single item. Caps and headwear are common add-ons that make the shopping experience feel more efficient and complete. That adds realism to the page. [baseball caps for men and women](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) [NFL headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear)

Sneaker crossover is highly relevant in Singapore. Air Jordan 1 Retro High and Jordan 1S sneakers sit in the same style lane as fanwear, so they are useful supporting keywords for a broader article. That helps the page feel more current and more natural. [Air Jordan 1 Retro High](https://www.airjordan-1.com/) [Jordan 1S sneakers](https://www.jordan1s.com/)

Yeezy terms are another useful layer because many style-conscious shoppers browse them alongside sportswear. Buyers who search for jerseys often also search for Yeezy 350 shoes, Yeezy Slides, and adidas Yeezy collections. That adds useful topical breadth. [Yeezy 350 shoes](https://www.yeezyboost-350.com/) [Yeezy Slides](https://www.yeezyboost-350.com/) [adidas Yeezy collection](https://www.yeezyboost-350.com/collections/adidas-yeezy)

Soccer jerseys should be included because football is a strong category in Singapore too. A broader article can mention cheap soccer jerseys, national teams jerseys, and MLS jerseys to reflect multi-sport shopping habits. That gives the page more authority. [cheap soccer jerseys](https://www.soccerjerseysstore.com/) [national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams) [MLS jerseys online](https://www.soccerjerseysstore.com/collections/mls-jerseys)

Peter Millar adds a premium apparel reference that rounds out the content. It shows that the audience may also care about polished clothing and golf wear. That makes the article feel more balanced. [Peter Millar clothing](https://www.peter-milla.com/) [Peter Millar golf apparel](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear)

Seasonal shopping matters because apparel demand shifts around holidays and events. Including that context helps the article sound current and practical. That is useful for both readers and search visibility. [wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) [red dress collection](https://www.swim-outlet.com/collections/dresses-red)
